### ISSUE TITLE
程序跑着跑着就报了错，直接挂掉的那种

### ISSUE THREAD

**Issue by Gxz-NGU** [lyqiangmny/zhihu-money-come#2]
直接上错误说明：
```
moneyCome 2020-12-24 02:29:03.449  INFO 9457 --- [nio-8088-exec-8] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [~~0x010x000x124Vx0x124/0x000x080x020x000x03Y0x100x110x15Q0x110x03k...]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Gxz-NGU** [comment]
查了一下问题，有人指出这个是尝试执行HTTPS请求，但没有启用HTTPS导致的。
[Tomcat: java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens](https://stackoverflow.com/questions/42218237/tomcat-java-lang-illegalargumentexception-invalid-character-found-in-method-na)

**Comment by Gxz-NGU** [comment]
感觉已经找到了方法，只要在`application.properties`文件中设置`server.max-http-header-size:16KB`
意思是增大了Http header的容量
附上不同服务器对http header大小的限制：

Web Server | Size Limit
-- | --
Apache | 8K
Nginx | 4K-8K
IIS | 8K-16K
Tomcat | 8K – 48K

来源：[What is the maximum size of HTTP header values?](https://www.tutorialspoint.com/What-is-the-maximum-size-of-HTTP-header-values)
